name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
    - name: Cache Eleventy .cache
      uses: actions/cache@v3
      with:
        path: ./.cache
        key: ${{ runner.os }}-eleventy-fetch-cache        
    - name: Build site
      run: |
        cd site
        echo "Building the site"
        npm install
        npm run build-ghpages
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        name: github-pages
        path: site/_site
    - name: Deploy to GitHub Pages from artifacts
      uses: actions/deploy-pages@v4